In [1]:
import pandas as pd
from bokeh.plotting import figure, show

In [2]:
df = pd.read_csv('results.csv')
df

,_id,isPb,wpm,acc,rawWpm,consistency,charStats,mode,mode2,quoteLength,...,punctuation,numbers,language,funbox,difficulty,lazyMode,blindMode,bailedOut,tags,timestamp
0,6226d8e3b75ef5d1e0d88da7,True,120.72,100.00,120.72,84.84,"151,0,0,0",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1646713060000
1,6226d8d1b75ef5d1e0d88d1d,NaN,97.53,96.99,106.33,84.12,"122,2,0,1",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1646713042000
2,6226d813b75ef5d1e0d0b1e2,NaN,94.34,97.54,94.34,69.27,"118,0,0,0",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1646712852000
3,6226d78db75ef5d1e0d0adac,NaN,108.66,97.87,111.85,84.08,"136,1,0,1",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1646712717000
4,6226d767b75ef5d1e0d0ac7c,NaN,111.93,98.61,115.12,88.09,"140,1,0,1",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1646712680000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,62144beb999bd5da83d2d622,True,96.58,91.98,105.38,74.49,"483,24,2,4",time,60,-1,...,False,False,english,none,normal,False,False,False,NaN,1645497323000
138,6202c1710004acbd88c4a25b,NaN,84.19,93.42,91.98,68.47,"421,13,1,3",time,60,-1,...,False,False,english,none,normal,False,False,False,NaN,1644347761000
139,6202bf650004acbd88b5eeb7,True,86.79,93.02,95.58,70.32,"434,16,2,3",time,60,-1,...,False,False,english,none,normal,False,False,False,NaN,1644347237000
140,6202bdaf0004acbd88ae8d75,True,96.74,96.85,101.53,80.30,"121,3,0,1",time,15,-1,...,False,False,english,none,normal,False,False,False,NaN,1644346799000
141,6202bcfd0004acbd88a735f6,True,93.97,98.37,97.17,82.09,"235,1,0,0",time,30,-1,...,False,False,english,none,normal,False,False,False,NaN,1644346621000

In [3]:
p = figure(title='Simple line example',
           x_axis_label='x',
           y_axis_label='y'
          )

p.line(x=df['rawWpm'],
       y=df['wpm'],
       legend_label='Temp', 
       line_width=2
      )
show(p)

In [8]:
import pandas_bokeh
import numpy as np
import pandas as pd

pandas_bokeh.output_file('thing.html')

#define the categorical variable
category = ['A','B','C']

#set random seed to make the dataset reproducible
np.random.seed(42)

#create a dataset
df_random = pd.DataFrame({'id': np.arange(0, 15),
                          'month':np.random.randint(1, 12, 15),
                          'sensor_1': np.random.uniform(0, 1,15),
                          'sensor_2': np.random.uniform(10, 15, 15),
                          'sensor_3': np.random.randint(0, 20, 15),
                          'category': np.random.choice(category, 15, p=[0.2, 0.4, 0.4])
                         })

In [9]:
#set index to id column
df_random=df_random.set_index('id')

In [10]:
# Plot1 - Line plot
p_line= df_random.groupby(['month']).mean().plot_bokeh(kind="line",y="sensor_2",color='#d01c8b',plot_data_points=True,show_figure=False)
# Plot2- Barplot
p_bar = df_random.groupby(['month']).mean().plot_bokeh(kind="bar",show_figure=False)

# Plot3- stacked bar chart
df_sensor=df_random.drop(['month'],axis=1)
p_stack=df_sensor.groupby(['category']).mean().plot_bokeh(kind='barh', stacked=True,show_figure=False)

#Plot4- Scatterplot
p_scatter = df_random.plot_bokeh(kind="scatter", x="month", y="sensor_2",category="category",show_figure=False)
#Plot5- Pie chart
p_pie= df_random.groupby(['category']).mean().plot_bokeh.pie(y='sensor_1',show_figure=False)

#Plot6- Histogram
p_hist=df_sensor.plot_bokeh(kind='hist', histogram_type="stacked",bins=6,show_figure=False)

__x__values_original

In [11]:
#Make Dashboard with Grid Layout: 
pandas_bokeh.plot_grid([[p_line, p_bar,p_stack],[p_scatter, p_pie,p_hist]], width=400)

Column(id='2978', ...)

In [12]:
import seaborn as sns
import plotly.express as px
import pandas as pd
from bokeh.plotting import output_file, show, figure

ImportError: cannot import name 'mpl' from 'bokeh' (C:\Users\steve\anaconda3\envs\dataviz\lib\site-packages\bokeh\__init__.py)

In [8]:
df = sns.load_dataset("tips")

In [13]:
px.violin(df,
          x="day", 
          y="total_bill"
         )

output_file("violin.html")

In [ ]:
show("violin.html")